### ISSUE TITLE
糖果分选机开始分选后传送带变速打不准

### ISSUE THREAD

**Issue by 3703781** [NanjingForestryUniversity/lowermachine#2]
这个版本[b01-d0.1-h1.0-p1.0-s0.1-a1.0](https://github.com/NanjingForestryUniversity/lowermachine/tree/b01-d0.1-h1.0-p1.0-s0.1-a1.0)
糖果分选机开始分选后传送带变速打不准
下面是维尔斯卢工的原话：
> 慢速调到能打了，做标记。调节到最快，打不到，再调到原先的慢速，也打不到，打的位置和快速一样的位置。停止分选，再开始分选，又能打到了。再调快打不准，再回原位也打不准，必须再停，再开。

**Comment by 3703781** [comment]
2023.02.06 我、程磊、薛胜、吴旻会到维尔斯出差解决

**Comment by 3703781** [comment]
原因是新换的控制传送带步进电机速度的旋转可调电阻阻值范围更大，导致可以将传送带调整到更快的速度。传送带速度太快，相机触发频率更高，上位机算法不能及时计算出结果
在版本[b01-d0.2-h1.1-p1.0-s1.0-a1.1](https://github.com/NanjingForestryUniversity/lowermachine/tree/b01-d0.2-h1.1-p1.0-s1.0-a1.1)中解决了这个问题，当存储上位机的图像数据队列为空时，将会给上位机发送报错信息。上位机收到后可以重新开始分选。同时让卢工固定传送带速度到约1m/s

**Comment by Chenglei98** [comment]
收到，miaow



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "NanjingForestryUniversity/lowermachine"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年2月8日(星期三) 晚上9:06
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [NanjingForestryUniversity/lowermachine] 糖果分选机开始分选后传送带变速打不准 (Issue #2)





 
原因是传送带速度太快，相机触发频率较高，上位机算法不能及时计算出结果
 在这个版本b01-d0.2-h1.1-p1.0-s1.0-a1.1中，当存储上位机的图像数据队列为空时，将会给上位机发送报错信息。上位机收到后可以重新开始分选。同时让卢工固定传送带速度到约1m/s。
