### ISSUE TITLE
关于刘英老师的刨花板缺陷检测和分选

### ISSUE THREAD

**Issue by laiyz11** [NanjingForestryUniversity/lowermachine#3]
刘老师的刨花板项目需要我们进行相机触发以及使用光电开关检测是否有木板在拍摄区域，具体要求是：
有木板在拍摄区域则需要依据编码器脉冲触发相机拍摄；
如果没有木板在拍摄区域则停止相机的触发脉冲；
需要同时触发多台相机

**Comment by 3703781** [comment]
已经新建分支 [b03-pwoodsorting-tchipboard1](https://github.com/NanjingForestryUniversity/lowermachine/tree/b03-pwoodsorting-tchipboard1)，用于这个项目
